vim.cmd [[
let g:coc_global_extensions = [
  \ '@yaegassy/coc-intelephense',
  \ 'coc-clangd',
  \ 'coc-css',
  \ 'coc-cssmodules',
  \ 'coc-eslint',
  \ 'coc-html',
  \ 'coc-htmlhint',
  \ 'coc-java',
  \ 'coc-json',
  \ 'coc-lua',
  \ 'coc-pairs',
  \ 'coc-prettier',
  \ 'coc-prisma',
  \ 'coc-python',
  \ 'coc-react-refactor',
  \ 'coc-rome',
  \ 'coc-sh',
  \ 'coc-snippets',
  \ 'coc-sql',
  \ 'coc-tailwindcss',
  \ 'coc-tsserver',
  \ 'coc-webview',
  \ ]
]]
